language: node_js
node_js:
  - "10"
  - "8"

jobs:
  include:
    - stage: coverage
      node_js: "10"
      script: yarn test --coverage && cat ./coverage/lcov.info | yarn coveralls && rm -rf coverage

notifications:
  email:
    on_success: never
